### ISSUE TITLE
Enable Github Actions

### ISSUE THREAD

**Issue by caioariede** [Tesorio/django-anon#26]
Wanna set up actions to include some tooling like linters, code coverage and perhaps replace CircleCI, example of what could be done:

https://github.com/codingjoe/django/blob/30962/flake8/.github/workflows/ci.yml

**Comment by FabioFleitas** [comment]
I don't know how to enable

**Comment by caioariede** [comment]
We'll have to hold a little bit

https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

> We hope you’ll try out the beta before GitHub Actions is generally available on November 13. We can’t wait to hear what you think!

Not sure you can try to opt-in like today

**Comment by caioariede** [comment]
@FabioFleitas can you please try to enable it today? It should be available

**Comment by FabioFleitas** [comment]
<img width="1680" alt="Screen Shot 2019-11-13 at 4 27 45 PM" src="https://user-images.githubusercontent.com/2321202/68816195-8d7afb00-0632-11ea-8d5d-2b11747db3bf.png">

**Comment by caioariede** [comment]
We've been notified by GH that Actions has been enabled for this repo 🎊🎉
