### ISSUE TITLE
New version to PyPi

### ISSUE THREAD

**Issue by tillgschwend** [Tesorio/django-anon#51]
Hello and thank you for your work

I ran into an issue where due to the method below on the BaseAnonymizer of the current pipy version.
```
    def _get_class_attributes(self):
        """ Return list of class attributes, which also includes methods and
            subclasses, ignoring any magic methods and reserved attributes
        """
        reserved_names = ["Meta", "clean",]

        return {
            name: self.__class__.__dict__[name]
            for name, value in self.__class__.__dict__.items()
            if not name.startswith("__") and name not in reserved_names
        }
```
The current master supplies a fix for it but its not the version that is on pypi. 
Would you mind shipping a new version that includes the updated version of the _get_class_attributes method?

Kind regards 
Till

**Comment by caioariede** [comment]
A new version has been released to PyPI: https://pypi.org/project/django-anon/0.2/
